-- 코드를 입력하세요
SELECT DATE_FORMAT(S.SALES_DATE, '%Y') AS YEAR,
    DATE_FORMAT(S.SALES_DATE, '%m') AS MONTH,
    GENDER,
    COUNT(DISTINCT I.USER_ID) AS USERS
FROM USER_INFO AS I
JOIN ONLINE_SALE AS S ON I.USER_ID = S.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY DATE_FORMAT(S.SALES_DATE, '%Y-%m'), I.GENDER
ORDER BY YEAR, MONTH, GENDER