-- 코드를 입력하세요

SET @user_count := (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = '2021');

SELECT YEAR(B.SALES_DATE) AS YEAR,
    MONTH(B.SALES_DATE) AS MONTH,
    ROUND(COUNT(DISTINCT A.USER_ID), 1) AS PUCHASED_USERS,
    ROUND(COUNT(DISTINCT A.USER_ID) / @user_count, 1) AS PUCHASED_RATIO
FROM USER_INFO AS A
    RIGHT JOIN ONLINE_SALE AS B USING(USER_ID)
WHERE YEAR(A.JOINED) = '2021'
GROUP BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE)


















# # SELECT COUNT(*) into @user_count FROM USER_INFO WHERE YEAR(JOINED) = '2021';
# SET @user_count := (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = '2021'),
#     @user_count1 := (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = '2022');

# SELECT YEAR(B.SALES_DATE) AS YEAR,
#     MONTH(B.SALES_DATE) AS MONTH,
#     COUNT(DISTINCT B.USER_ID) AS PUCHASED_USERS,
#     ROUND(COUNT(DISTINCT B.USER_ID) / @user_count, 1) AS PUCHASED_RATIO
# FROM USER_INFO AS A
#     JOIN ONLINE_SALE AS B USING(USER_ID)
# WHERE YEAR(A.JOINED) = '2021'
# GROUP BY YEAR, MONTH


























# # WITH T AS (
# #     SELECT DISTINCT(USER_ID)
# #     FROM USER_INFO AS A
# #     RIGHT OUTER JOIN ONLINE_SALE AS B USING(USER_ID)
# #     WHERE YEAR(A.JOINED) = '2021'
# # )

# SELECT COUNT(USER_ID) into @user_count FROM USER_INFO WHERE YEAR(JOINED) = 2021;

# SELECT YEAR(B.SALES_DATE) AS YEAR,
#     MONTH(B.SALES_DATE) AS MONTH,
#     COUNT(DISTINCT USER_ID) AS PUCHASED_USERS,
#     ROUND(COUNT(DISTINCT USER_ID) / @USER_COUNT, 1) AS PUCHASED_RATIO
# FROM USER_INFO AS A
#     JOIN ONLINE_SALE AS B USING(USER_ID)
# WHERE YEAR(A.JOINED) = '2021'
# GROUP BY YEAR, MONTH
# ORDER BY YEAR, MONTH

# # SELECT COUNT(*) FROM USER_INFO RIGHT OUTER JOIN ONLINE_SALE USING(USER_ID) WHERE YEAR(JOINED) = '2021' AND MONTH(SALES_DATE) = '3'