-- 코드를 입력하세요
WITH RECURSIVE TIME AS (
    SELECT 0 AS HOURS
    UNION ALL
    SELECT HOURS+1 FROM TIME
    WHERE HOURS < 23
)

SELECT TIME.HOURS AS HOUR, IFNULL(COUNT(ANIMAL_OUTS.ANIMAL_ID), '0') AS COUNT
FROM TIME
LEFT OUTER JOIN ANIMAL_OUTS ON HOUR(ANIMAL_OUTS.DATETIME) = TIME.HOURS
GROUP BY HOUR
ORDER BY HOUR